"""Additional bias diagnostics for behavior-derived relevance supervision.

The analyses are associative. They identify possible logging, exposure,
coverage, user-propensity, and presentation biases; they cannot establish
causal effects from observational logs generated by an existing ranker.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from src.config import CACHE_DIR, FIGURES_DIR, OUTPUT_DIR

os.environ.setdefault("MPLCONFIGDIR", str(CACHE_DIR / "matplotlib"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency, spearmanr

from src.relevance_eda import load_behavioral_table, wilson_interval


BIAS_DIR = OUTPUT_DIR / "relevance" / "eda" / "bias"
BIAS_METRICS_PATH = BIAS_DIR / "bias_diagnostics_metrics.json"
BIAS_REPORT_PATH = BIAS_DIR / "bias_diagnostics_report.md"
JUDGMENT_COVERAGE_PATH = BIAS_DIR / "query_judgment_coverage.csv"
SESSION_LENGTH_PATH = BIAS_DIR / "session_length_bias.csv"
DOCTOR_PROPENSITY_PATH = BIAS_DIR / "doctor_engagement_propensity.csv"
CONTENT_EXPOSURE_PATH = BIAS_DIR / "content_exposure_bias.csv"
REPRESENTATION_PATH = BIAS_DIR / "inventory_vs_exposure_representation.csv"
TEMPORAL_PATH = BIAS_DIR / "weekly_engagement.csv"
ASSOCIATION_PATH = BIAS_DIR / "bias_association_screen.csv"
TIMESTAMP_TIES_PATH = BIAS_DIR / "inferred_rank_timestamp_ties.csv"
BIAS_FIGURE_PATH = FIGURES_DIR / "phase6_relevance_bias_diagnostics.png"


def _gini(values: pd.Series) -> float:
    array = np.sort(values.to_numpy(dtype=float))
    if len(array) == 0 or np.isclose(array.sum(), 0):
        return 0.0
    ranks = np.arange(1, len(array) + 1)
    return float((2 * np.dot(ranks, array)) / (len(array) * array.sum()) - (len(array) + 1) / len(array))


def query_judgment_coverage(table: pd.DataFrame) -> pd.DataFrame:
    corpus_size = int(table["content_id"].nunique())
    result = (
        table.groupby("query_id", as_index=False)
        .agg(
            query_intent=("query_intent", "first"),
            query_language=("query_language", "first"),
            sessions=("session_id", "nunique"),
            impression_rows=("content_id", "size"),
            observed_content=("content_id", "nunique"),
            engaged_rows=("has_engagement", "sum"),
        )
    )
    result["judgment_coverage"] = result["observed_content"] / corpus_size
    result["has_observed_positive"] = result["engaged_rows"].gt(0)
    return result.sort_values(["has_observed_positive", "judgment_coverage", "query_id"])


def session_length_bias(table: pd.DataFrame) -> pd.DataFrame:
    sessions = (
        table.groupby("session_id", as_index=False)
        .agg(
            list_length=("content_id", "size"),
            engaged_results=("has_engagement", "sum"),
        )
    )
    sessions["has_engagement"] = sessions["engaged_results"].gt(0)
    rows: list[dict[str, Any]] = []
    for length, group in sessions.groupby("list_length", sort=True):
        impressions = int(group["list_length"].sum())
        engaged = int(group["engaged_results"].sum())
        any_engaged = int(group["has_engagement"].sum())
        low, high = wilson_interval(engaged, impressions)
        rows.append(
            {
                "list_length": int(length),
                "sessions": int(len(group)),
                "sessions_with_engagement": any_engaged,
                "session_any_engagement_rate": float(any_engaged / len(group)),
                "impressions": impressions,
                "engaged_impressions": engaged,
                "per_impression_engagement_rate": float(engaged / impressions),
                "per_impression_ci95_low": low,
                "per_impression_ci95_high": high,
                "mean_engaged_results_per_session": float(group["engaged_results"].mean()),
            }
        )
    return pd.DataFrame(rows)


def doctor_propensity(table: pd.DataFrame) -> pd.DataFrame:
    result = (
        table.groupby("doctor_id", as_index=False)
        .agg(
            impressions=("query_id", "size"),
            sessions=("session_id", "nunique"),
            unique_queries=("query_id", "nunique"),
            engaged=("has_engagement", "sum"),
        )
    )
    result["engagement_rate"] = result["engaged"] / result["impressions"]
    intervals = [wilson_interval(int(row.engaged), int(row.impressions)) for row in result.itertuples()]
    result["engagement_ci95_low"] = [item[0] for item in intervals]
    result["engagement_ci95_high"] = [item[1] for item in intervals]
    return result.sort_values(["engagement_rate", "impressions", "doctor_id"])


def content_exposure_bias(table: pd.DataFrame) -> pd.DataFrame:
    result = (
        table.groupby("content_id", as_index=False)
        .agg(
            content_type=("content_type", "first"),
            content_source_type=("content_source_type", "first"),
            content_language=("content_language", "first"),
            content_publication_year=("content_publication_year", "first"),
            impressions=("query_id", "size"),
            unique_queries=("query_id", "nunique"),
            rank1_impressions=("inferred_rank", lambda values: int(values.eq(1).sum())),
            engaged=("has_engagement", "sum"),
        )
    )
    result["engagement_rate"] = result["engaged"] / result["impressions"]
    result["rank1_share"] = result["rank1_impressions"] / result["impressions"]
    return result.sort_values(["impressions", "engagement_rate"], ascending=[False, False])


def inventory_vs_exposure(table: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    unique_content = table.drop_duplicates("content_id")
    unique_queries = table.drop_duplicates("query_id")
    specifications = [
        ("content_type", unique_content, table),
        ("content_language", unique_content, table),
        ("content_source_type", unique_content, table),
        ("content_publication_year", unique_content, table),
        ("query_intent", unique_queries, table),
        ("query_language", unique_queries, table),
    ]
    for dimension, inventory, exposures in specifications:
        inventory_share = inventory[dimension].value_counts(normalize=True, dropna=False)
        exposure_share = exposures[dimension].value_counts(normalize=True, dropna=False)
        inventory_count = inventory[dimension].value_counts(dropna=False)
        exposure_count = exposures[dimension].value_counts(dropna=False)
        for value in sorted(set(inventory_share.index) | set(exposure_share.index), key=str):
            baseline = float(inventory_share.get(value, 0.0))
            observed = float(exposure_share.get(value, 0.0))
            rows.append(
                {
                    "dimension": dimension,
                    "value": str(value),
                    "inventory_items": int(inventory_count.get(value, 0)),
                    "inventory_share": baseline,
                    "impressions": int(exposure_count.get(value, 0)),
                    "impression_share": observed,
                    "representation_ratio": observed / baseline if baseline else np.nan,
                }
            )
    return pd.DataFrame(rows)


def weekly_engagement(table: pd.DataFrame) -> pd.DataFrame:
    working = table.copy()
    working["week"] = working["timestamp"].dt.to_period("W").astype(str)
    rows: list[dict[str, Any]] = []
    for week, group in working.groupby("week", sort=True):
        engaged = int(group["has_engagement"].sum())
        low, high = wilson_interval(engaged, len(group))
        rows.append(
            {
                "week": week,
                "impressions": int(len(group)),
                "engaged": engaged,
                "engagement_rate": float(engaged / len(group)),
                "engagement_ci95_low": low,
                "engagement_ci95_high": high,
            }
        )
    return pd.DataFrame(rows)


def association_screen(table: pd.DataFrame) -> pd.DataFrame:
    """Screen marginal associations using Cramer's V effect size.

    P-values are included for auditability but are anti-conservative because
    impressions are clustered within sessions, doctors, queries, and content.
    """
    working = table.copy()
    lengths = working.groupby("session_id").size()
    working["session_length"] = working["session_id"].map(lengths)
    working["week"] = working["timestamp"].dt.to_period("W").astype(str)
    variables = (
        "doctor_id",
        "session_length",
        "query_intent",
        "query_language",
        "content_type",
        "content_source_type",
        "content_language",
        "content_publication_year",
        "inferred_rank",
        "week",
    )
    rows: list[dict[str, Any]] = []
    for variable in variables:
        contingency = pd.crosstab(working[variable], working["has_engagement"])
        chi_square, p_value, _, expected = chi2_contingency(contingency)
        denominator = len(working) * min(contingency.shape[0] - 1, contingency.shape[1] - 1)
        cramer_v = float(np.sqrt(chi_square / denominator)) if denominator else 0.0
        rates = working.groupby(variable)["has_engagement"].mean()
        rows.append(
            {
                "variable": variable,
                "groups": int(contingency.shape[0]),
                "cramers_v": cramer_v,
                "chi_square_p_value_naive": float(p_value),
                "minimum_expected_cell": float(expected.min()),
                "minimum_group_rate": float(rates.min()),
                "maximum_group_rate": float(rates.max()),
                "rate_range": float(rates.max() - rates.min()),
                "clustered_rows_caveat": True,
            }
        )
    return pd.DataFrame(rows).sort_values("cramers_v", ascending=False)


def inferred_rank_timestamp_ties(table: pd.DataFrame) -> pd.DataFrame:
    counts = (
        table.groupby(["session_id", "query_id", "timestamp"], as_index=False)
        .size()
        .rename(columns={"size": "impressions_at_same_timestamp"})
    )
    tied = counts[counts["impressions_at_same_timestamp"].gt(1)]
    return pd.DataFrame(
        [
            {
                "impressions": int(len(table)),
                "tied_timestamp_groups": int(len(tied)),
                "impressions_in_tied_groups": int(tied["impressions_at_same_timestamp"].sum()),
                "share_impressions_in_tied_groups": float(
                    tied["impressions_at_same_timestamp"].sum() / len(table)
                ),
                "extra_rows_beyond_first_in_ties": int(
                    (tied["impressions_at_same_timestamp"] - 1).sum()
                ),
                "largest_tied_group": int(tied["impressions_at_same_timestamp"].max()),
                "tie_breaker": "impression_id",
            }
        ]
    )


def _plot_bias_diagnostics(
    coverage: pd.DataFrame,
    session_length: pd.DataFrame,
    doctors: pd.DataFrame,
    content: pd.DataFrame,
) -> None:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(2, 2, figsize=(13, 9))

    axes[0, 0].hist(coverage["judgment_coverage"] * 100, bins=15, color="#4C78A8", edgecolor="white")
    axes[0, 0].set(title="Per-query behavioral judgment coverage", xlabel="Corpus observed for query (%)", ylabel="Queries")
    axes[0, 0].axvline(coverage["judgment_coverage"].mean() * 100, color="#D62728", linestyle="--", label="Mean")
    axes[0, 0].legend()

    axes[0, 1].plot(
        session_length["list_length"], session_length["per_impression_engagement_rate"],
        marker="o", label="Per-impression engagement",
    )
    axes[0, 1].plot(
        session_length["list_length"], session_length["session_any_engagement_rate"],
        marker="s", label="Session has any engagement",
    )
    axes[0, 1].set(title="Outcome varies with session list length", xlabel="Results in session", ylabel="Rate", ylim=(-0.03, 1.05))
    axes[0, 1].legend()
    axes[0, 1].grid(alpha=0.2)

    axes[1, 0].scatter(doctors["impressions"], doctors["engagement_rate"], alpha=0.7, color="#59A14F")
    axes[1, 0].axhline(
        doctors["engaged"].sum() / doctors["impressions"].sum(),
        color="#D62728", linestyle="--", label="Global rate",
    )
    axes[1, 0].set(title="Doctor engagement propensity", xlabel="Doctor impressions", ylabel="Engagement rate")
    axes[1, 0].legend()
    axes[1, 0].grid(alpha=0.2)

    axes[1, 1].scatter(content["impressions"], content["engagement_rate"], alpha=0.65, color="#F28E2B")
    axes[1, 1].set(title="Content exposure and observed engagement", xlabel="Content impressions", ylabel="Engagement rate")
    axes[1, 1].grid(alpha=0.2)

    fig.tight_layout()
    fig.savefig(BIAS_FIGURE_PATH, dpi=180, bbox_inches="tight")
    plt.close(fig)


def _markdown_table(frame: pd.DataFrame, max_rows: int = 30) -> str:
    view = frame.head(max_rows).copy()
    headers = [str(column) for column in view.columns]
    body = [[str(value) for value in row] for row in view.to_numpy()]
    return "\n".join(
        [
            "| " + " | ".join(headers) + " |",
            "| " + " | ".join("---" for _ in headers) + " |",
            *("| " + " | ".join(row) + " |" for row in body),
        ]
    )


def build_report(
    metrics: dict[str, Any],
    session_length: pd.DataFrame,
    associations: pd.DataFrame,
    temporal: pd.DataFrame,
    ties: pd.DataFrame,
) -> str:
    return "\n".join(
        [
            "# Additional Bias Diagnostics for Behavioral Relevance", "",
            "These diagnostics identify associations and censoring in the supplied logs. They do not establish causal bias because the existing ranker, query mix, doctor mix, and logging process are not randomized.", "",
            "## 1. Judgment-pool and exposure bias", "",
            f"Only {metrics['observed_query_content_pairs']:,} of {metrics['possible_query_content_pairs']:,} "
            f"possible query-content pairs are observed ({metrics['global_judgment_coverage']:.1%}); "
            f"{metrics['unjudged_query_content_pairs']:,} pairs are unjudged. Treating every unobserved corpus item "
            "as grade 0 would convert lack of exposure into an irrelevant label and favor the historical ranker's pool.", "",
            f"Per-query coverage has median {metrics['median_query_judgment_coverage']:.1%} and ranges from "
            f"{metrics['minimum_query_judgment_coverage']:.1%} to {metrics['maximum_query_judgment_coverage']:.1%}. "
            "Phase 7 and retrieval evaluation should distinguish judged impressions from unjudged candidates and report pool coverage.", "",
            "## 2. Outcome-conditioned session and query opportunity", "", _markdown_table(
                session_length[["list_length", "sessions", "session_any_engagement_rate", "per_impression_engagement_rate"]].round(3)
            ), "",
            f"All {metrics['five_result_sessions']} five-result sessions have no engagement, while every 11- and "
            f"12-result session has at least one engagement. Also, all {metrics['queries_without_positive']} queries "
            "without a positive occur among single-session queries; every multi-session query has a positive. This "
            "pattern is consistent with outcome-conditioned sampling or synthetic construction, so exposure count and "
            "session length must not become relevance features.", "",
            "## 3. Doctor propensity bias", "",
            f"Doctor-level engagement ranges from {metrics['doctor_rate_min']:.1%} to {metrics['doctor_rate_max']:.1%}; "
            f"the interquartile range is {metrics['doctor_rate_iqr']:.1%}. Among doctors with at least 50 impressions, "
            f"rates still range from {metrics['doctor50_rate_min']:.1%} to {metrics['doctor50_rate_max']:.1%}. The marginal "
            f"doctor association is the largest screen effect (Cramer's V={metrics['doctor_cramers_v']:.3f}). This can "
            "reflect user propensity, query mix, or logging differences—not intrinsic content relevance.", "",
            "## 4. Content popularity and presentation bias", "",
            f"Content exposure is not extremely concentrated (Gini={metrics['content_exposure_gini']:.3f}; top decile "
            f"receives {metrics['content_top_decile_exposure_share']:.1%} of impressions), but exposure count and observed "
            f"engagement rate are strongly correlated (Spearman rho={metrics['content_exposure_engagement_spearman']:.3f}). "
            "Because positive events are part of the logged impression pool, popularity and relevance cannot be separated "
            "from these data alone. Content ID, source type, and historical exposure frequency should not directly set grades.", "",
            "Source type and content type also show marginal engagement differences. These may reflect attractiveness, "
            "snippet quality, ranker policy, or query mix; use them as evaluation slices rather than label weights.", "",
            "At the inventory level, content language and content type are exposed roughly in proportion to their corpus "
            "shares. Query opportunity is less even: Treatment Change / Escalation is exposed at "
            f"{metrics['query_intent_max_representation_ratio']:.2f} times its query-inventory share, while Safety / "
            f"Contraindication is exposed at {metrics['query_intent_min_representation_ratio']:.2f} times its share. "
            "Intent-level metrics should therefore report both query counts and exposure counts.", "",
            "## 5. Inferred-rank measurement error", "", _markdown_table(ties.round(3)), "",
            f"Serving timestamps tie for {metrics['timestamp_tied_impression_share']:.1%} of impressions. Their internal "
            "order is resolved by impression ID, so `inferred_rank` is partly arbitrary. Any propensity correction should "
            "be a sensitivity analysis unless a true position field becomes available.", "",
            "## 6. Temporal coverage", "", _markdown_table(temporal.round(3)), "",
            f"The logs cover only {metrics['date_span_days']} days in one calendar month. Weekly engagement ranges from "
            f"{metrics['weekly_rate_min']:.1%} to {metrics['weekly_rate_max']:.1%}, but seasonality and drift cannot be "
            "estimated from this window.", "",
            "## Marginal association screen", "", _markdown_table(
                associations[["variable", "groups", "cramers_v", "chi_square_p_value_naive", "rate_range"]].round(4)
            ), "",
            "These p-values treat impression rows as independent even though rows are clustered by session, doctor, "
            "query, and content. They are included only as a screen; effect sizes and domain plausibility matter more.", "",
            "## Phase 7 safeguards", "",
            "- Never label unshown query-content pairs as irrelevant; track them as unjudged.",
            "- Keep exposure count, session length, doctor ID, content ID, source type, and inferred rank out of the grade rule.",
            "- Use those fields for stratification, grouped splits, propensity sensitivity, and monitoring instead.",
            "- Preserve session-level evidence and aggregate repeated pairs with exposure and disagreement fields.",
            "- Report the 150 no-positive queries separately from queries eligible for positive-dependent metrics.",
            "- Avoid double-counting event type and dwell as independent evidence; their distributions are tightly coupled.",
            "- Use query- or session-clustered uncertainty estimates rather than naive impression-level p-values.",
            "- Treat language analyses as inconclusive: observed rates are similar, but the sample cannot rule out retrieval-quality bias.", "",
        ]
    )


def build_bias_eda_artifacts() -> dict[str, Path]:
    table = load_behavioral_table()
    coverage = query_judgment_coverage(table)
    sessions = session_length_bias(table)
    doctors = doctor_propensity(table)
    content = content_exposure_bias(table)
    representation = inventory_vs_exposure(table)
    temporal = weekly_engagement(table)
    associations = association_screen(table)
    ties = inferred_rank_timestamp_ties(table)

    total_pairs = int(table["query_id"].nunique() * table["content_id"].nunique())
    observed_pairs = int(table[["query_id", "content_id"]].drop_duplicates().shape[0])
    doctor50 = doctors[doctors["impressions"].ge(50)]
    exposure_rho = spearmanr(content["impressions"], content["engagement_rate"])
    doctor_association = associations.set_index("variable").loc["doctor_id"]
    intent_representation = representation[representation["dimension"].eq("query_intent")]
    metrics: dict[str, Any] = {
        "possible_query_content_pairs": total_pairs,
        "observed_query_content_pairs": observed_pairs,
        "unjudged_query_content_pairs": total_pairs - observed_pairs,
        "global_judgment_coverage": float(observed_pairs / total_pairs),
        "minimum_query_judgment_coverage": float(coverage["judgment_coverage"].min()),
        "median_query_judgment_coverage": float(coverage["judgment_coverage"].median()),
        "maximum_query_judgment_coverage": float(coverage["judgment_coverage"].max()),
        "queries_without_positive": int((~coverage["has_observed_positive"]).sum()),
        "no_positive_queries_with_multiple_sessions": int(
            ((~coverage["has_observed_positive"]) & coverage["sessions"].gt(1)).sum()
        ),
        "five_result_sessions": int(sessions.loc[sessions["list_length"].eq(5), "sessions"].iloc[0]),
        "five_result_session_any_engagement_rate": float(
            sessions.loc[sessions["list_length"].eq(5), "session_any_engagement_rate"].iloc[0]
        ),
        "eleven_twelve_result_session_any_engagement_rate": float(
            table.assign(session_length=table["session_id"].map(table.groupby("session_id").size()))
            .loc[lambda x: x["session_length"].isin([11, 12])]
            .groupby("session_id")["has_engagement"].any().mean()
        ),
        "doctor_rate_min": float(doctors["engagement_rate"].min()),
        "doctor_rate_max": float(doctors["engagement_rate"].max()),
        "doctor_rate_iqr": float(
            doctors["engagement_rate"].quantile(0.75) - doctors["engagement_rate"].quantile(0.25)
        ),
        "doctors_with_at_least_50_impressions": int(len(doctor50)),
        "doctor50_rate_min": float(doctor50["engagement_rate"].min()),
        "doctor50_rate_max": float(doctor50["engagement_rate"].max()),
        "doctor_cramers_v": float(doctor_association["cramers_v"]),
        "content_exposure_gini": _gini(content["impressions"]),
        "content_top_decile_exposure_share": float(
            content.nlargest(int(np.ceil(len(content) * 0.10)), "impressions")["impressions"].sum()
            / content["impressions"].sum()
        ),
        "content_exposure_engagement_spearman": float(exposure_rho.statistic),
        "content_exposure_engagement_p_value_naive": float(exposure_rho.pvalue),
        "query_intent_min_representation_ratio": float(
            intent_representation["representation_ratio"].min()
        ),
        "query_intent_max_representation_ratio": float(
            intent_representation["representation_ratio"].max()
        ),
        "timestamp_tied_impression_share": float(ties.loc[0, "share_impressions_in_tied_groups"]),
        "date_start": str(table["timestamp"].min()),
        "date_end": str(table["timestamp"].max()),
        "date_span_days": int(table["timestamp"].dt.normalize().nunique()),
        "weekly_rate_min": float(temporal["engagement_rate"].min()),
        "weekly_rate_max": float(temporal["engagement_rate"].max()),
        "causal_claims_supported": False,
    }

    BIAS_DIR.mkdir(parents=True, exist_ok=True)
    coverage.to_csv(JUDGMENT_COVERAGE_PATH, index=False)
    sessions.to_csv(SESSION_LENGTH_PATH, index=False)
    doctors.to_csv(DOCTOR_PROPENSITY_PATH, index=False)
    content.to_csv(CONTENT_EXPOSURE_PATH, index=False)
    representation.to_csv(REPRESENTATION_PATH, index=False)
    temporal.to_csv(TEMPORAL_PATH, index=False)
    associations.to_csv(ASSOCIATION_PATH, index=False)
    ties.to_csv(TIMESTAMP_TIES_PATH, index=False)
    BIAS_METRICS_PATH.write_text(
        json.dumps(metrics, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    BIAS_REPORT_PATH.write_text(
        build_report(metrics, sessions, associations, temporal, ties), encoding="utf-8"
    )
    _plot_bias_diagnostics(coverage, sessions, doctors, content)

    return {
        "metrics": BIAS_METRICS_PATH,
        "report": BIAS_REPORT_PATH,
        "query_coverage": JUDGMENT_COVERAGE_PATH,
        "session_length": SESSION_LENGTH_PATH,
        "doctor_propensity": DOCTOR_PROPENSITY_PATH,
        "content_exposure": CONTENT_EXPOSURE_PATH,
        "representation": REPRESENTATION_PATH,
        "temporal": TEMPORAL_PATH,
        "associations": ASSOCIATION_PATH,
        "timestamp_ties": TIMESTAMP_TIES_PATH,
        "figure": BIAS_FIGURE_PATH,
    }


if __name__ == "__main__":
    for artifact, path in build_bias_eda_artifacts().items():
        print(f"{artifact}: {path}")
